name: Budowanie wersji Release

on:
  push:
    tags:
      - 'v*' # Tag wersji

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Konfiguracja Javy 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Budowanie JAR (Maven)
        run: mvn clean package

      - name: Przygotowanie plików do paczki
        run: |
            copy src\main\resources\config.properties target\

      - name: Tworzenie EXE i wersji Portable
        run: |
                # 1. Tworzenie standardowego instalatora EXE
                jpackage --type exe --name "SymulacjaEpidemii" --input target --main-jar SymulacjaEpidemii.jar --main-class epidemic.Main --win-dir-chooser --win-shortcut --dest output
                
                # 2. Tworzenie gotowego folderu z aplikacją i JRE
                jpackage --type app-image --name "SymulacjaEpidemii_Portable" --input target --main-jar SymulacjaEpidemii.jar --main-class epidemic.Main --dest portable
                
                # 3. Kopiowanie pliku config bezpośrednio do folderu głównego wersji Portable
                copy src\main\resources\config.properties portable\SymulacjaEpidemii_Portable\
                
                # 4. Pakowanie folderu do archiwum ZIP
                powershell Compress-Archive -Path portable\SymulacjaEpidemii_Portable\* -DestinationPath output\SymulacjaEpidemii_v${{ github.ref_name }}_Portable.zip
      - name: Generowanie Javadoc
        run: | 
          mvn javadoc:javadoc
          echo "" > target/site/apidocs/.nojekyll

      - name: Publikacja Javadoc na GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          force_orphan: true
      - name: Publikacja na GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
                  target/SymulacjaEpidemii.jar
                  output/*.exe
                  output/*.zip
                  src/main/resources/config.properties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}